### ISSUE TITLE
EndScene

### ISSUE THREAD

**Issue by gabberworld** [jasonsx/Hook-DirectX-8.1-with-detours#1]
what todo when directx 8 game not use EndScene, or its there but hook may not find that

**Comment by jasonsx** [comment]
Well you can use present

**Comment by gabberworld** [comment]
thanks im kind off new at this direct x stuff and there not many examples for directx 8, there is horever is allot for directx 9. 

i want also point out that FindWindow may not work for all the games. for example where i want hook, it not work, i needed search for that the other solution

**Comment by jasonsx** [comment]
The 2 version of directx 8&9 are the same 
Only some changed at all not much as you think and there is a lot of way to get the main window
